Cine-NT1-Grupo2/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cine_NT1_Grupo2.Context;
using Cine_NT1_Grupo2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;

namespace Cine_NT1_Grupo2.Controllers
{

    [Authorize]
    public class ClienteController : Controller
    {
        private readonly CineContext _context;
        private readonly Seguridad seguridad = new VerificacionBasica();
        public ClienteController(CineContext context)
        {
            _context = context;
        }


        // GET: Cliente
        [Authorize]
        public async Task<IActionResult> Index()

        {

            List<Cliente> clienteDevolver;

            if (User.FindFirstValue(ClaimTypes.Role).ToString() != Rol.ADMIN.ToString())
            {
                var idCliente = User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();

                clienteDevolver = await _context.Cliente.Where(s => s.id.ToString() == idCliente).ToListAsync();
            }
            else
            {
                clienteDevolver = await _context.Cliente.ToListAsync();
            }


                return View(clienteDevolver);
        }


        // GET: Cliente/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

           

               

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            if (User.FindFirstValue(ClaimTypes.Role).ToString() != Rol.ADMIN.ToString())
            {
                var idDelCliente = (int)Int64.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

                if (cliente.id != idDelCliente)
                {
                    return NotFound();
                }

            }



            return View(cliente);
        }

        // GET: Cliente/Create

       [AllowAnonymous]
        public IActionResult Registrarse()
        {
            return View();
        }


        // POST: Cliente/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

     
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Registrarse([Bind("id,Nombre,Apellido,Mail,pass")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                // Vamos a chequear si el mail existe
                bool mailExiste = _context.Cliente.Any(c => c.Mail == cliente.Mail);

                if (mailExiste)
                {

                    /* Agregar validaciones al model: ver 
                     * https://desarrolloweb.com/articulos/validaciones-aspnet-mvc-donet.html
                     */
                    /*En el caso de que no queremos que se le asigne a una propiedad, debeboms poner simplemente ""
                     * en el primer parametro. (ej , aqui donde dice Mail, iria ""*/
                    ModelState.AddModelError("Mail", "Ya existe un usuario con este mail");

                    return View(cliente);
                }
                //valida la contraseña a travez de la clase que implementa la interfaz segruidad
                if (seguridad.validarPass(cliente.pass))
                {
                    cliente.Rol = Rol.USUARIO;
                    _context.Add(cliente);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "contraseña NO VALIDA: NO puede estar vacia, ser menor a 8 caracteres y debe contener una mayuscula una minúscula y un numero");
                }
                
            }
            return View(cliente);
        }

        // GET: Cliente/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var cliente = await _context.Cliente.FindAsync(id);

            

                if (cliente == null)
            {
                return NotFound();
            }


            if (User.FindFirstValue(ClaimTypes.Role).ToString() != Rol.ADMIN.ToString())
            {
                var idDelCliente = (int)Int64.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

                if (cliente.id != idDelCliente)
                {
                    return NotFound();
                }

            }


            return View(cliente);
        }

        // POST: Cliente/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Nombre,Apellido,Mail,pass")] Cliente cliente)
        {

            if (User.FindFirstValue(ClaimTypes.Role).ToString() != Rol.ADMIN.ToString())
            {
                var idDelCliente = (int)Int64.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

                if (cliente.id != idDelCliente)
                {
                    
                    TempData["MensajeCliente"] = "hubo un error, intente nuevamente";
                    return RedirectToAction(nameof(Index));
                }

            }


            if (id != cliente.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                bool mailExiste = _context.Cliente.Any(c => c.Mail == cliente.Mail);

                if (mailExiste)
                {
                                        
                    ModelState.AddModelError("Mail", "Ya existe un usuario con este mail");

                    return View(cliente);
                }
               
                if (seguridad.validarPass(cliente.pass))
                {
                    /* Sino lo aclaro lo modifica a 0*/
                    cliente.Rol = Rol.USUARIO;
                                      
                }
                else
                {
                    ModelState.AddModelError("", "contraseña NO VALIDA: NO puede estar vacia, ser menor a 8 caracteres y debe contener una mayuscula una minúscula y un numero");
                    return View(cliente);
                }


                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Cliente/Delete/5
        [Authorize(Roles = nameof(Rol.ADMIN))]
        public async Task<IActionResult> Delete(int? id)
        {




            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }



        // POST: Cliente/Delete/5
        [Authorize(Roles = nameof(Rol.ADMIN))]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.Cliente.FindAsync(id);

            if (cliente != null)
            {

                /*Antes de borrar al cliente seteo los asientos en 0 de sus entradas */
                var entradasModel = await _context.Entrada.Where(s => s.ClienteId.ToString() == cliente.id.ToString()).Include(entrada => entrada.Funcion.Pelicula)
                 .Include(entrada => entrada.Funcion.Asientos).ToListAsync();

                foreach (var ent in entradasModel)
                {
                    ent.Asiento.ClienteId = 0;
                }
            }



            _context.Cliente.Remove(cliente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = nameof(Rol.ADMIN))]
        private bool ClienteExists(int id)
        {
            return _context.Cliente.Any(e => e.id == id);
        }

        /*No entiendo el motivo pero si o si el string debe llamarse returnUrl */
        /*RTA https://www.it-swarm-es.com/es/asp.net/como-funciona-la-redireccion-returnurl-en-asp.net-mvc5/1044284456/ */
        /* https://stackoverflow.com/questions/20123612/how-am-i-supposed-to-use-returnurl-viewbag-returnurl-in-mvc-4 */

        [AllowAnonymous]
        public IActionResult Loguearse(string returnUrl)
        {
            TempData["UrlAEnviar"] = returnUrl;
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Loguearse(string mail, string pass)
        {
            var UrlAEnviar = TempData["UrlAEnviar"] as string;

            if (!string.IsNullOrEmpty(mail) && !string.IsNullOrEmpty(pass))

Cine-NT1-Grupo2/Controllers/TarjetaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cine_NT1_Grupo2.Context;
using Cine_NT1_Grupo2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;

namespace Cine_NT1_Grupo2.Controllers
{
    [Authorize]

    public class TarjetaController : Controller
    {
        private readonly CineContext _context;

        public TarjetaController(CineContext context)
        {
            _context = context;
        }

        // GET: Tarjeta
        public async Task<IActionResult> Index()

        {
            List<Tarjeta> tarjetaDevolver;

            if (User.FindFirstValue(ClaimTypes.Role).ToString() != Rol.ADMIN.ToString())
            {
                var idCliente = User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();

                tarjetaDevolver = await _context.Tarjeta.Where(s => s.ClienteId.ToString() == idCliente).ToListAsync();
            }
            else
            {
                tarjetaDevolver = await _context.Tarjeta.ToListAsync();
            }


            return View(tarjetaDevolver);
        }

        // GET: Tarjeta/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarjeta = await _context.Tarjeta
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tarjeta == null)
            {
                return NotFound();
            }

            if (User.FindFirstValue(ClaimTypes.Role).ToString() != Rol.ADMIN.ToString())
            {
                var idDelCliente = (int)Int64.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

                if (tarjeta.ClienteId != idDelCliente)
                {
                    return NotFound();
                }

            }

            return View(tarjeta);
        }

        // GET: Tarjeta/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tarjeta/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, Numero ,FechaDeVencimiento,CodigoSeguridad,Nombre")] Tarjeta tarjeta)
        {

            var texto = User.FindFirstValue(ClaimTypes.NameIdentifier);

            tarjeta.ClienteId = (int)Int64.Parse(texto);

            if (ModelState.IsValid)
            {
                //*****ACA VALIDAMOS QUE LA TARJETA NO PUEDA CARGARSE MISMO NUMERO Y MISMO TITULAR****
                bool tarjetaExiste = _context.Tarjeta.Any(t => ((t.Numero == tarjeta.Numero) && (t.Nombre == tarjeta.Nombre)));


                if (tarjetaExiste)
                {
                    ModelState.AddModelError("Nombre", "La tarjeta ya se encuentra cargada en Sistema");

                   
                    return View(tarjeta);
                }

                _context.Add(tarjeta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tarjeta);
        }

        // GET: Tarjeta/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarjeta = await _context.Tarjeta
                .FirstOrDefaultAsync(m => m.Id == id);

            if (tarjeta == null)
            {
                return NotFound();
            }

            if (User.FindFirstValue(ClaimTypes.Role).ToString() != Rol.ADMIN.ToString())
            {
                var idDelCliente = (int)Int64.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));

                if (tarjeta.ClienteId != idDelCliente)
                {
                    return NotFound();
                }

            }

            return View(tarjeta);
        }

        // POST: Tarjeta/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Numero ,FechaDeVencimiento,CodigoSeguridad,Nombre")] Tarjeta tarjeta)
        {
            if (id != tarjeta.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tarjeta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TarjetaExists(tarjeta.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tarjeta);
        }

        // GET: Tarjeta/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tarjeta = await _context.Tarjeta
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tarjeta == null)
            {
                return NotFound();
            }

            return View(tarjeta);
        }

        // POST: Tarjeta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tarjeta = await _context.Tarjeta.FindAsync(id);
            _context.Tarjeta.Remove(tarjeta);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TarjetaExists(int id)
        {
            return _context.Tarjeta.Any(e => e.Id == id);
        }
    }
}

Cine-NT1-Grupo2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Prado Diessler Federico Werner Nahuel- Safe Facundo Nadir- Toppino Mariano Ariel">
    <meta name="Keywords" content="CINE, Peliculas, online, entradas, estrenos, promociones">
    <title>@ViewData["Title"] - Bienvenido a CINEMA-ORT </title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bakbak+One&display=swap" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3 navbar-dark">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">
                 Cinema-ORT</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="nav nav-pills flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>



                        @if (User.Identity.IsAuthenticated)
                        {

                            
                            //esto es lo que puede ver el USUARIO AUTENTICADO EN EL NAV
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Entrada" asp-action="Index">Entrada</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Cliente" asp-action="Index">Cliente</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Funcion" asp-action="Index">Funciones</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Pelicula" asp-action="Index">Cartelera</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Tarjeta" asp-action="Index">Medio De Pago</a>
                            </li>

                           
                        }
                       
                    </ul>
                </div>
            </div>
            <div class="loginNavBar flex-row-reverse">
                
                <ul class="nav nav-pills">
                    @if (!User.Identity.IsAuthenticated)
                    {   
                        <li class="nav-item float-right">
                            <a class="nav-link active" asp-area="" asp-controller="Cliente" asp-action="Loguearse">Iniciar Sesión</a>
                        </li>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item float-right">
                            <p class="nav-link text-white" asp-area="">Bienvenido @User.FindFirstValue(ClaimTypes.GivenName)!</p>
                        </li>

                        <li class="nav-item">
                            <form asp-controller="Cliente" asp-action="Desloguearse">
                                <button type="submit" class="nav-link alert-danger">Cerrar Sesión</button>
                            </form>
                        </li>
                    }
                </ul>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div>
                @*
            <h4>
                Contacto
            </h4>
            <p>
                (011) 4561-1654 <br />
                (011) 4324-4324<br />
                AtencionClientes@cinema-ort.com<br />

            </p>

        </div>

        <div>
            <p> ¡Seguinos en nuestras redes sociales! </p>
            <ul>
                <li> <a href="https://www.facebook.com/%27%3E/"><"Facebook">  </a> </li>
                <li> <a href="https://www.instagram.com/%22%3E/"><"instagram"> </a> </li>
                <li> <a href="https://twitter.com/%22%3E/"><"twitter">  </a> </li>
            </ul>
                *@
            </div>
            &copy; 2021 - CinemaORT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Politica de Privacidad</a>
        </div>

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>